import { AsyncStateProvider, ThemeProvider } from "@omariosouto/common-ui-web/providers";
import "@omariosouto/common-ui-web/globals.css";
import "./globals.css" // Import to enable local themes
import { localThemes } from "./consts";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AsyncStateProvider>
          <ThemeProvider
            extraThemes={localThemes}
          >
            {children}
          </ThemeProvider>
        </AsyncStateProvider>
      </body>
    </html>
  )
}
