import { ThemeProvider } from "@omariosouto/common-ui-web/components";
import { AsyncStateProvider } from "@omariosouto/common-ui-web/state";
import "@omariosouto/common-ui-web/globals.css";
import "./globals.css" // Import to enable local themes

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AsyncStateProvider>
          <ThemeProvider
            extraThemes={["theme-emerald", "theme-emerald-dark"]}
          >
            {children}
          </ThemeProvider>
        </AsyncStateProvider>
      </body>
    </html>
  )
}
