name: "[CI] Continuous Integration"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Node and GitHub Packages authentication
      - name: "Set up Node and GitHub Packages"
        uses: actions/setup-node@v4
        with:
          # always-auth ensures npm always sends credentials when installing packages
          always-auth: true
          # Configure the default registry for the given scope
          registry-url: "https://registry.npmjs.org"
          scope: "@omariosouto"

      - name: "Configure GitHub Packages registry for @omariosouto"
        run: |
          npm config set @omariosouto:registry "https://npm.pkg.github.com/"
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}

      - name: "Install Dependencies"
        run: npm ci

      - name: "Test"
        run: npm run test
  build-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Node and GitHub Packages authentication
      - name: "Set up Node and GitHub Packages"
        uses: actions/setup-node@v4
        with:
          # always-auth ensures npm always sends credentials when installing packages
          always-auth: true
          # Configure the default registry for the given scope
          registry-url: "https://registry.npmjs.org"
          scope: "@omariosouto"

      - name: "Configure GitHub Packages registry for @omariosouto"
        run: |
          npm config set @omariosouto:registry "https://npm.pkg.github.com/"
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}

      - name: "Install Dependencies"
        run: npm ci

      - name: "Test"
        run: npm run build:example
